spring.application.name=gringotts-sync
# ==========================================
# Configuration de la communication avec PHP
# ==========================================
# Remplace par l'URL exacte de ton serveur PHP
# Configuration de la communication avec PHP
kyntus.php.api.url=http://host.docker.internal:8080/api/sync
kyntus.php.api.key=KYNTUS_SUPER_SECRET_SYNC_KEY_2026_!@#

# (Kheli l'ba9i dyal les configurations dyalek hna, walakin mss7 mnhom les Emojis)